language: c
before_install:
- sudo apt-get update
- sudo apt-get build-dep wine
script:
- "./configure --enable-win64"
- make
- tar -czvf wine.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: gAZw5hMUDcvZ+a3XCS51mT29CXl+0TKNB3euE/sKgM0+nhZK9CXOjuT6zNt45WnNlfMc7KeSDkDlXY+rzgKFPbK6ydQnNwzuudFvdnbkezC8bFiQXPk1EcChb75hYURThiaoEAeg/YKcIBEjT9LQNbV+8eaFgkKrSoQjePUBLtZTtcNDC1g0t6N7H4KWcpqBi/JwkTx3F7e421PH5BRwvbuIEdA8YXGXWbCTapIp2bG+LLkaxnNuQlHKJewBb+qvP5LCjLq2qrFxn+Ql0jNB5hL7wUOCVNZBwU0qiTLGEixZUwwL8efsHCoz0tmBBmD8e+UbqT7g5bOEFAH+lR+q7MAt6mV9vNVnaRjITarz8MUihDhtkfFIyl8poejFxmBxPBhQEbUPkA4pg/4YEmUn/DrE/647XoTFxdJV4Fpz2nsxjRC5In93mFalgUzKqLvQqRFPGKgYZ8maG7sbsqeKb7Rg+wORMvND9Ym7SvFHSsmKxHeoe1maj4cYFny69n96o3cOqL1nS8iwZrmpLekRb/4N8JhRPe2XaLBjf+P2Uk5QkQaPstaFB4xI8b3EM8NGCxCnh3oDP8Dd2bZtXYtF4WlWd8yBFR/vocH7rLn35Ylp9ssofml5y1gNrEBm6etRIdMn7Ma7Xj4jp4E+3sG/NvceolGrZ+gmDq8p4KaShnU=
  file: wine.tar.gz
  skip_cleanup: true
  on:
    repo: sigmaSd/wine
